---
blank_issues_enabled: false
contact_links:
  - name: LancasterAQ Community Support
    url: https://github.com/lgouldsbrough/LancasterAQ/discussions
    about: Please ask and answer questions here.
